# -*- coding: utf-8 -*-
"""S3. Abstracts_Classification (DistilBERT).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wm8CJtB8arn-t4fjQEXCf1Bay4seTW78
"""

!pip install torch

# Import required libraries
from transformers import pipeline
import pandas as pd
import torch

# Step 1: Load DistilBERT zero-shot classification pipeline
classifier = pipeline("zero-shot-classification", model="typeform/distilbert-base-uncased-mnli", device=0 if torch.cuda.is_available() else -1)
# device=0 uses GPU if available, else CPU
'''
classifier = pipeline(
    "zero-shot-classification",
    model="facebook/bart-large-mnli",
    device=0 if torch.cuda.is_available() else -1
)
'''

# Step 2: Define candidate labels based on your criteria
candidate_labels = [
    "electrical load forecasting in residential areas only",
    "non-residential contexts",
    "commercial buildings",
    "manufacturing",
    "factory",
    "agricultural energy systems",
    "primary focus on anomaly detection",
    "load monitoring as primary focus",
    "thermal load forecasting",
    "heating or cooling systems",
    "electric vehicles",
    "explicitly stating this is a literature review or a survey paper",
    "solar energy",
    "wind energy",
    "renewable energy",
    "unclear or mixed focus"
]

# Step 3: Load abstracts
#file_path = 'Title Screened.xlsx'
file_path = "Ex_Abs.xlsx"
df = pd.DataFrame()
try:
    df = pd.read_excel(file_path)
except FileNotFoundError:
    print("Error: Excel file not found. Please make sure the path is correct and the file exists.")
    # Exit or handle the error appropriately
    exit()


# Encode the abstracts
keys = df["Key"].tolist()
abstracts = df["Abstract"].tolist()

# Step 4: Classify abstracts
results = []
for key, abstract in zip(keys,abstracts):
    # Perform zero-shot classification
    result = classifier(abstract, candidate_labels, multi_label=False)
    predicted_label = result["labels"][0]  # Take the top-scoring label
    confidence = result["scores"][0]       # Confidence score for the top label
    results.append({"key":key, "abstract_text": abstract, "predicted_label": predicted_label, "confidence": confidence})

# Step 5: Save results to CSV
results_df = pd.DataFrame(results)
results_df.to_excel("predicted_abstracts.xlsx", index=False)
print("Predictions saved to 'predicted_abstracts.xlsx'")

