# -*- coding: utf-8 -*-
"""S2. Copy of Abstracts_Classification (Cross-Encoder).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jLnFwwbOJfVgoiZ85bu01VcCEgewTRUh
"""

!pip install torch

# Import required libraries
from sentence_transformers import CrossEncoder
import pandas as pd
import torch

# Step 1: Load CrossEncoder model (better for NLI/entailment classification)
model = CrossEncoder("cross-encoder/nli-deberta-v3-base", device="cuda" if torch.cuda.is_available() else "cpu")

# Step 2: Define simplified candidate labels
candidate_labels = [
    "residential electrical load forecasting",
    "non-residential electrical forecasting",
    "agricultural energy systems",
    "anomaly detection",
    "load monitoring",
    "thermal load forecasting",
    "electric vehicles",
    "literature review",
    "solar energy",
    "wind energy",
    "renewable energy",
    "unclear or mixed focus"
]

# Step 3: Load abstracts from Excel
file_path = "Ex_Abs.xlsx"
df = pd.DataFrame()
try:
    df = pd.read_excel(file_path)
except FileNotFoundError:
    print("Error: Excel file not found. Please make sure the path is correct and the file exists.")
    exit()

# Step 4: Classify abstracts
results = []
keys = df["Key"].tolist()
abstracts = df["Abstract"].tolist()

for key, abstract in zip(keys, abstracts):
    # Create text-label pairs for cross-encoder
    pairs = [(abstract, label) for label in candidate_labels]
    scores = model.predict(pairs)  # Output: entailment scores

    scores = [float(s[2]) for s in scores]

    # Sort by highest score
    label_scores = list(zip(candidate_labels, scores))
    label_scores.sort(key=lambda x: x[1], reverse=True)

    best_label, best_score = label_scores[0]

    # Optional verdict mapping (e.g. include/exclude/maybe)
    if best_score >= 0.7 and "residential" in best_label:
        verdict = "include"
    elif best_score >= 0.7:
        verdict = "exclude"
    elif best_score >= 0.4:
        verdict = "maybe"
    else:
        verdict = "low confidence"

    results.append({
        "key": key,
        "abstract_text": abstract,
        "predicted_label": best_label,
        "confidence": round(best_score, 4),
        "verdict": verdict
    })

# Step 5: Save results
results_df = pd.DataFrame(results)
results_df.to_excel("predicted_abstracts_cross_encoder.xlsx", index=False)
print("Predictions saved to 'predicted_abstracts_cross_encoder.xlsx'")

